name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
  ref:
    required: true
    description: "git branch or tag"
  kubernetes_endpoint:
    required: true
    description: "https url to api controller"
  kubernetes_token:
    required: true
    description: "access token"
  kubernetes_image:
    required: true
    description: "docker image"
  kubernetes_environment_variables:
    required: true
    description: "array of key value pairs"
  terraform_backend_credentials:
    required: true
    description: "credentials file"
  terraform_backend_bucket:
    required: true
    description: "terraform backend bucket name"
  terraform_backend_prefix:
    required: true
    description: "terraform backend prefix"
  npm_pre:
    required: false
    description: "npm first line""
  npm_token:
    required: false
    description: "npm token"
  npm_registry:
    required: false
    description: "npm registry"
runs:
  using: "node12"
  main: "dist/index.js"
#  using: "docker"
#  image: Dockerfile
