name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
  name:
    required: true
    description: "service name"
  kubernetes_endpoint:
    required: true
    description: "https url to api controller"
  kubernetes_token:
    required: true
    description: "access token"
runs:
  using: "node12"
  main: "dist/index.js"
